/**
 * Données et suggestions multi-marchés pour le Dashboard Parieur SerenBet.
 * Offre la totale des matchs du jour (Big Leagues : PL, La Liga, Ligue 1, Bundesliga, Serie A, Champions League)
 * avec plusieurs paris suggérés par match : Vainqueur 1X2, Buts, Corners, Cartons Jaunes, Tirs, Fautes.
 */

import type { UpcomingMatch, BettingPick } from "@/lib/types";

const DEMO_BANKROLL = 1000;

function getDateISO(daysOffset: number, hours: number = 20, minutes: number = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
}

export const DEMO_UPCOMING_MATCHES: UpcomingMatch[] = [
  // --- AUJOURD'HUI (Matchs du Jour - Big Leagues & Qualifs) ---
  {
    id: "match-today-01",
    sport: "football",
    competition: "Premier League",
    home_team: "Arsenal",
    away_team: "Chelsea",
    commence_time: getDateISO(0, 18, 30),
    model_probs: { home: 0.53, draw: 0.23, away: 0.24 },
    market_odds: { home: 1.95, draw: 3.60, away: 4.10 },
    best_bookmaker: "Betclic",
    best_outcome: "home",
    best_edge: 8.4,
    best_ev: 0.064,
    is_demo: true,
    stat_rates: {
      lambda_goals_home: 1.95,
      lambda_goals_away: 1.10,
      lambda_corners_home: 6.4,
      lambda_corners_away: 4.2,
      lambda_cards_home: 2.1,
      lambda_cards_away: 2.6,
      lambda_fouls_home: 11.5,
      lambda_fouls_away: 13.2,
      lambda_shots_home: 15.2,
      lambda_shots_away: 10.8,
      lambda_sot_home: 5.6,
      lambda_sot_away: 3.8,
      lambda_offsides_home: 2.1,
      lambda_offsides_away: 1.8,
    },
  },
  {
    id: "match-today-02",
    sport: "football",
    competition: "Champions League - Qualifications",
    home_team: "Fenerbahçe",
    away_team: "Lugano",
    commence_time: getDateISO(0, 19, 0),
    model_probs: { home: 0.68, draw: 0.20, away: 0.12 },
    market_odds: { home: 1.45, draw: 4.50, away: 7.00 },
    best_bookmaker: "Winamax",
    best_outcome: "home",
    best_edge: 8.9,
    best_ev: 0.086,
    is_demo: true,
    stat_rates: {
      lambda_goals_home: 2.45,
      lambda_goals_away: 0.70,
      lambda_corners_home: 7.1,
      lambda_corners_away: 3.1,
      lambda_cards_home: 1.9,
      lambda_cards_away: 2.9,
      lambda_fouls_home: 10.8,
      lambda_fouls_away: 14.1,
      lambda_shots_home: 16.8,
      lambda_shots_away: 7.9,
      lambda_sot_home: 6.1,
      lambda_sot_away: 2.6,
      lambda_offsides_home: 2.2,
      lambda_offsides_away: 1.4,
    },
  },
  {
    id: "match-today-03",
    sport: "football",
    competition: "Amical International",
    home_team: "Liverpool",
    away_team: "Real Betis",
    commence_time: getDateISO(0, 21, 0),
    model_probs: { home: 0.62, draw: 0.22, away: 0.16 },
    market_odds: { home: 1.58, draw: 4.10, away: 5.80 },
    best_bookmaker: "Unibet",
    best_outcome: "home",
    best_edge: 7.2,
    best_ev: 0.058,
    is_demo: true,
    stat_rates: {
      lambda_goals_home: 2.30,
      lambda_goals_away: 0.95,
      lambda_corners_home: 6.8,
      lambda_corners_away: 3.6,
      lambda_cards_home: 1.5,
      lambda_cards_away: 2.2,
      lambda_fouls_home: 10.1,
      lambda_fouls_away: 12.4,
      lambda_shots_home: 16.4,
      lambda_shots_away: 8.8,
      lambda_sot_home: 5.9,
      lambda_sot_away: 3.1,
      lambda_offsides_home: 2.3,
      lambda_offsides_away: 1.6,
    },
  },

  // --- DEMAIN (Matchs à venir - Big Leagues) ---
  {
    id: "match-tomorrow-01",
    sport: "football",
    competition: "Amical International",
    home_team: "Real Madrid",
    away_team: "AC Milan",
    commence_time: getDateISO(1, 20, 0),
    model_probs: { home: 0.55, draw: 0.23, away: 0.22 },
    market_odds: { home: 1.85, draw: 3.75, away: 4.20 },
    best_bookmaker: "Winamax",
    best_outcome: "home",
    best_edge: 7.8,
    best_ev: 0.059,
    is_demo: true,
    stat_rates: {
      lambda_goals_home: 2.15,
      lambda_goals_away: 1.05,
      lambda_corners_home: 6.3,
      lambda_corners_away: 4.0,
      lambda_cards_home: 1.4,
      lambda_cards_away: 1.9,
      lambda_fouls_home: 9.8,
      lambda_fouls_away: 11.2,
      lambda_shots_home: 15.8,
      lambda_shots_away: 10.2,
      lambda_sot_home: 5.7,
      lambda_sot_away: 3.7,
      lambda_offsides_home: 2.3,
      lambda_offsides_away: 1.8,
    },
  },
  {
    id: "match-tomorrow-02",
    sport: "football",
    competition: "Amical International",
    home_team: "Manchester City",
    away_team: "Barcelona",
    commence_time: getDateISO(1, 21, 15),
    model_probs: { home: 0.42, draw: 0.26, away: 0.32 },
    market_odds: { home: 2.05, draw: 3.70, away: 3.80 },
    best_bookmaker: "1xBet",
    best_outcome: "away",
    best_edge: 9.2,
    best_ev: 0.075,
    is_demo: true,
    stat_rates: {
      lambda_goals_home: 1.70,
      lambda_goals_away: 1.45,
      lambda_corners_home: 6.6,
      lambda_corners_away: 5.4,
      lambda_cards_home: 1.6,
      lambda_cards_away: 2.0,
      lambda_fouls_home: 10.4,
      lambda_fouls_away: 11.8,
      lambda_shots_home: 14.5,
      lambda_shots_away: 13.1,
      lambda_sot_home: 5.2,
      lambda_sot_away: 4.5,
      lambda_offsides_home: 2.0,
      lambda_offsides_away: 2.4,
    },
  },

  // --- J+2 (Ligue 1 & Bundesliga & Serie A) ---
  {
    id: "match-j2-01",
    sport: "football",
    competition: "Ligue 1",
    home_team: "PSG",
    away_team: "Olympique de Marseille",
    commence_time: getDateISO(2, 20, 45),
    model_probs: { home: 0.61, draw: 0.21, away: 0.18 },
    market_odds: { home: 1.55, draw: 4.20, away: 6.50 },
    best_bookmaker: "Unibet",
    best_outcome: "home",
    best_edge: 6.2,
    best_ev: 0.051,
    is_demo: true,
    stat_rates: {
      lambda_goals_home: 2.45,
      lambda_goals_away: 0.85,
      lambda_corners_home: 7.0,
      lambda_corners_away: 3.7,
      lambda_cards_home: 2.6,
      lambda_cards_away: 3.3,
      lambda_fouls_home: 13.5,
      lambda_fouls_away: 15.4,
      lambda_shots_home: 17.4,
      lambda_shots_away: 8.9,
      lambda_sot_home: 6.3,
      lambda_sot_away: 3.0,
      lambda_offsides_home: 2.5,
      lambda_offsides_away: 1.9,
    },
  },
  {
    id: "match-j2-02",
    sport: "football",
    competition: "Serie A",
    home_team: "Inter Milan",
    away_team: "Juventus",
    commence_time: getDateISO(2, 21, 0),
    model_probs: { home: 0.46, draw: 0.29, away: 0.25 },
    market_odds: { home: 2.10, draw: 3.40, away: 3.75 },
    best_bookmaker: "Bwin",
    best_outcome: "home",
    best_edge: 6.5,
    best_ev: 0.052,
    is_demo: true,
    stat_rates: {
      lambda_goals_home: 1.65,
      lambda_goals_away: 0.95,
      lambda_corners_home: 5.9,
      lambda_corners_away: 4.2,
      lambda_cards_home: 2.2,
      lambda_cards_away: 2.7,
      lambda_fouls_home: 12.8,
      lambda_fouls_away: 14.1,
      lambda_shots_home: 14.1,
      lambda_shots_away: 9.8,
      lambda_sot_home: 4.9,
      lambda_sot_away: 3.4,
      lambda_offsides_home: 1.8,
      lambda_offsides_away: 1.9,
    },
  },
];

// --- PANOPLIE DE PARIS ET SUGGESTIONS MULTI-MARCHÉS PAR MATCH ---
export const DEMO_PICKS: BettingPick[] = [
  // --- ARSENAL vs CHELSEA (Match du Jour) ---
  {
    id: "pick-ars-01",
    match_id: "match-today-01",
    home_team: "Arsenal",
    away_team: "Chelsea",
    competition: "Premier League",
    sport: "football",
    commence_time: DEMO_UPCOMING_MATCHES[0].commence_time,
    market_type: "1X2",
    outcome: "home",
    outcome_label: "Arsenal gagne",
    odds: 1.95,
    model_probability: 0.53,
    market_probability: 0.513,
    edge: 0.084,
    expected_value: 0.064,
    confidence: "high",
    kelly_fraction: 0.022,
    kelly_stake_euros: Math.round(DEMO_BANKROLL * 0.022),
    bookmaker: "Betclic",
    is_suspicious: false,
    is_demo: true,
  },
  {
    id: "pick-ars-02",
    match_id: "match-today-01",
    home_team: "Arsenal",
    away_team: "Chelsea",
    competition: "Premier League",
    sport: "football",
    commence_time: DEMO_UPCOMING_MATCHES[0].commence_time,
    market_type: "corners",
    outcome: "corners_over_9.5",
    outcome_label: "Plus de 9.5 Corners dans le match",
    odds: 1.82,
    model_probability: 0.62,
    market_probability: 0.549,
    edge: 0.071,
    expected_value: 0.068,
    confidence: "high",
    kelly_fraction: 0.025,
    kelly_stake_euros: Math.round(DEMO_BANKROLL * 0.025),
    bookmaker: "Winamax",
    is_suspicious: false,
    is_demo: true,
  },
  {
    id: "pick-ars-03",
    match_id: "match-today-01",
    home_team: "Arsenal",
    away_team: "Chelsea",
    competition: "Premier League",
    sport: "football",
    commence_time: DEMO_UPCOMING_MATCHES[0].commence_time,
    market_type: "cards",
    outcome: "cards_over_3.5",
    outcome_label: "Plus de 3.5 Cartons Jaunes",
    odds: 1.75,
    model_probability: 0.67,
    market_probability: 0.571,
    edge: 0.099,
    expected_value: 0.085,
    confidence: "high",
    kelly_fraction: 0.028,
    kelly_stake_euros: Math.round(DEMO_BANKROLL * 0.028),
    bookmaker: "Unibet",
    is_suspicious: false,
    is_demo: true,
  },
  {
    id: "pick-ars-04",
    match_id: "match-today-01",
    home_team: "Arsenal",
    away_team: "Chelsea",
    competition: "Premier League",
    sport: "football",
    commence_time: DEMO_UPCOMING_MATCHES[0].commence_time,
    market_type: "shots",
    outcome: "sot_home_over_4.5",
    outcome_label: "Arsenal : Plus de 4.5 Tirs Cadrés",
    odds: 1.68,
    model_probability: 0.69,
    market_probability: 0.595,
    edge: 0.095,
    expected_value: 0.079,
    confidence: "high",
    kelly_fraction: 0.026,
    kelly_stake_euros: Math.round(DEMO_BANKROLL * 0.026),
    bookmaker: "Betclic",
    is_suspicious: false,
    is_demo: true,
  },

  // --- FENERBAHÇE vs LUGANO (Match du Jour) ---
  {
    id: "pick-fen-01",
    match_id: "match-today-02",
    home_team: "Fenerbahçe",
    away_team: "Lugano",
    competition: "Champions League - Qualif",
    sport: "football",
    commence_time: DEMO_UPCOMING_MATCHES[1].commence_time,
    market_type: "1X2",
    outcome: "home",
    outcome_label: "Fenerbahçe gagne",
    odds: 1.45,
    model_probability: 0.68,
    market_probability: 0.655,
    edge: 0.089,
    expected_value: 0.086,
    confidence: "high",
    kelly_fraction: 0.032,
    kelly_stake_euros: Math.round(DEMO_BANKROLL * 0.032),
    bookmaker: "Betclic",
    is_suspicious: false,
    is_demo: true,
  },
  {
    id: "pick-fen-02",
    match_id: "match-today-02",
    home_team: "Fenerbahçe",
    away_team: "Lugano",
    competition: "Champions League - Qualif",
    sport: "football",
    commence_time: DEMO_UPCOMING_MATCHES[1].commence_time,
    market_type: "goals",
    outcome: "goals_over_2.5",
    outcome_label: "Plus de 2.5 Buts dans le match",
    odds: 1.65,
    model_probability: 0.65,
    market_probability: 0.606,
    edge: 0.066,
    expected_value: 0.0725,
    confidence: "high",
    kelly_fraction: 0.024,
    kelly_stake_euros: Math.round(DEMO_BANKROLL * 0.024),
    bookmaker: "Winamax",
    is_suspicious: false,
    is_demo: true,
  },
  {
    id: "pick-fen-03",
    match_id: "match-today-02",
    home_team: "Fenerbahçe",
    away_team: "Lugano",
    competition: "Champions League - Qualif",
    sport: "football",
    commence_time: DEMO_UPCOMING_MATCHES[1].commence_time,
    market_type: "corners",
    outcome: "corners_home_over_5.5",
    outcome_label: "Fenerbahçe : Plus de 5.5 Corners",
    odds: 1.72,
    model_probability: 0.71,
    market_probability: 0.581,
    edge: 0.129,
    expected_value: 0.121,
    confidence: "high",
    kelly_fraction: 0.035,
    kelly_stake_euros: Math.round(DEMO_BANKROLL * 0.035),
    bookmaker: "Unibet",
    is_suspicious: false,
    is_demo: true,
  },

  // --- LIVERPOOL vs REAL BETIS (Match du Jour) ---
  {
    id: "pick-liv-01",
    match_id: "match-today-03",
    home_team: "Liverpool",
    away_team: "Real Betis",
    competition: "Amical International",
    sport: "football",
    commence_time: DEMO_UPCOMING_MATCHES[2].commence_time,
    market_type: "1X2",
    outcome: "home",
    outcome_label: "Liverpool gagne",
    odds: 1.58,
    model_probability: 0.62,
    market_probability: 0.632,
    edge: 0.072,
    expected_value: 0.058,
    confidence: "medium",
    kelly_fraction: 0.018,
    kelly_stake_euros: Math.round(DEMO_BANKROLL * 0.018),
    bookmaker: "Unibet",
    is_suspicious: false,
    is_demo: true,
  },
  {
    id: "pick-liv-02",
    match_id: "match-today-03",
    home_team: "Liverpool",
    away_team: "Real Betis",
    competition: "Amical International",
    sport: "football",
    commence_time: DEMO_UPCOMING_MATCHES[2].commence_time,
    market_type: "goals",
    outcome: "btts_yes",
    outcome_label: "Les deux équipes marquent (Oui)",
    odds: 1.78,
    model_probability: 0.61,
    market_probability: 0.561,
    edge: 0.076,
    expected_value: 0.085,
    confidence: "high",
    kelly_fraction: 0.026,
    kelly_stake_euros: Math.round(DEMO_BANKROLL * 0.026),
    bookmaker: "Betclic",
    is_suspicious: false,
    is_demo: true,
  },

  // --- MANCHESTER CITY vs BARCELONA (Match Demain) ---
  {
    id: "pick-mci-01",
    match_id: "match-tomorrow-02",
    home_team: "Manchester City",
    away_team: "Barcelona",
    competition: "Amical International",
    sport: "football",
    commence_time: DEMO_UPCOMING_MATCHES[4].commence_time,
    market_type: "1X2",
    outcome: "away",
    outcome_label: "Barcelona gagne",
    odds: 3.80,
    model_probability: 0.32,
    market_probability: 0.263,
    edge: 0.092,
    expected_value: 0.075,
    confidence: "high",
    kelly_fraction: 0.028,
    kelly_stake_euros: Math.round(DEMO_BANKROLL * 0.028),
    bookmaker: "1xBet",
    is_suspicious: false,
    is_demo: true,
  },
  {
    id: "pick-mci-02",
    match_id: "match-tomorrow-02",
    home_team: "Manchester City",
    away_team: "Barcelona",
    competition: "Amical International",
    sport: "football",
    commence_time: DEMO_UPCOMING_MATCHES[4].commence_time,
    market_type: "corners",
    outcome: "corners_over_10.5",
    outcome_label: "Plus de 10.5 Corners dans le match",
    odds: 2.10,
    model_probability: 0.54,
    market_probability: 0.476,
    edge: 0.084,
    expected_value: 0.134,
    confidence: "high",
    kelly_fraction: 0.030,
    kelly_stake_euros: Math.round(DEMO_BANKROLL * 0.030),
    bookmaker: "Winamax",
    is_suspicious: false,
    is_demo: true,
  },
];

export function valueBetToPick(
  vb: {
    id: string;
    home_team: string;
    away_team: string;
    competition: string | null;
    sport: string;
    commence_time: string | null;
    outcome: string;
    odds: number;
    model_probability: number;
    market_fair_probability: number;
    edge: number;
    expected_value: number;
    bookmaker: string | null;
    is_suspicious: boolean;
  },
  bankroll: number,
  kellyMultiplier: number = 0.25
): BettingPick {
  const outcomeMap: Record<string, "home" | "draw" | "away"> = {
    home: "home",
    draw: "draw",
    away: "away",
    "1": "home",
    x: "draw",
    "2": "away",
  };
  const normalizedOutcome = outcomeMap[vb.outcome.toLowerCase()] ?? "home";

  const outcomeLabel =
    normalizedOutcome === "home"
      ? `${vb.home_team} gagne`
      : normalizedOutcome === "away"
        ? `${vb.away_team} gagne`
        : "Match nul";

  const kellyRaw = vb.edge / (vb.odds - 1);
  const kelly = Math.min(Math.max(kellyRaw * kellyMultiplier, 0), 0.05);

  const confidence: "high" | "medium" | "low" =
    vb.edge >= 0.07 && !vb.is_suspicious
      ? "high"
      : vb.edge >= 0.04 && !vb.is_suspicious
        ? "medium"
        : "low";

  return {
    id: vb.id,
    match_id: vb.id,
    home_team: vb.home_team,
    away_team: vb.away_team,
    competition: vb.competition ?? vb.sport,
    sport: vb.sport,
    commence_time: vb.commence_time ?? new Date().toISOString(),
    market_type: "1X2",
    outcome: normalizedOutcome,
    outcome_label: outcomeLabel,
    odds: vb.odds,
    model_probability: vb.model_probability,
    market_probability: vb.market_fair_probability,
    edge: vb.edge,
    expected_value: vb.expected_value,
    confidence,
    kelly_fraction: kelly,
    kelly_stake_euros: Math.round(bankroll * kelly),
    bookmaker: vb.bookmaker ?? "—",
    is_suspicious: vb.is_suspicious,
    is_demo: false,
  };
}
